##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200430       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("ssc.Rmd")' 2> log >> log
